language: rust
rust:
  - 1.42.0 # minimum supported toolchain
  - stable
  - beta
  - nightly
os: linux
env:
  global:
    - CLIPPY=1

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - env: CLIPPY
  include:
    - env: CLIPPY
      name: Lints
      rust: 1.42.0
      install:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo clippy --lib --tests --all-features -- -D clippy::complexity -W clippy::pedantic -W clippy::nursery
        - cargo fmt -- --check

branches:
  only:
    - master

script:
  - cargo test --all --all-features

notifications:
  email:
    on_success: never
