[package]
name = "mockito"
version = "0.30.0"
authors = ["Florin Lipan <florinlipan@gmail.com>"]
license = "MIT"
homepage = "https://github.com/lipanski/mockito"
repository = "https://github.com/lipanski/mockito"
documentation = "https://docs.rs/mockito"
description = "HTTP mocking for Rust."
keywords = ["mock", "mocks", "http", "webmock", "webmocks"]
categories = ["development-tools::testing", "web-programming"]
exclude = ["/.appveyor.yml", "/.travis.yml", "/benchmarks.txt", "/docs/", "/slides.pdf"]
edition = "2018"

[badges]
travis-ci = { repository = "lipanski/mockito", branch = "master" }
appveyor = { repository = "lipanski/mockito", branch = "master", service = "github" }

[dependencies]
rand = "0.8"
httparse = "1.3.3"
regex = "1.0.5"
lazy_static = "1.1.0"
serde_json = "1.0.17"
similar = "2.1"

colored = { version = "2.0.0", optional = true }
log = "0.4.6"
assert-json-diff = "2.0.0"
serde_urlencoded = "0.7.0"

[dev-dependencies]
env_logger = "0.8.2"
testing_logger = "0.1"

[features]
default = ["color"]
color = ["colored"]
