name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test-default:
    name: Test the minimum supported toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          profile: minimal
          override: true
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test --no-default-features

  test-latest:
    name: Test on latest stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test --no-default-features

  test-nightly:
    name: Test on nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test --no-default-features

